'use client';

import { Download } from 'lucide-react';

function triggerDownload(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildWordCSV(words) {
  const header = 'rank,word,frequency,percentage,stopword,stem';
  const rows = (words || []).map((w, i) =>
    `${i + 1},${w.word},${w.frequency},${w.percentage},${w.isStopword},${w.stem || ''}`
  );
  return [header, ...rows].join('\n');
}

function buildKeywordCSV(keywords) {
  const header = 'rank,keyword,tfidf_score';
  const rows = (keywords || []).map(k => `${k.rank},${k.keyword},${k.score}`);
  return [header, ...rows].join('\n');
}

function buildSummaryTXT(summary) {
  if (!summary?.sentences?.length) return 'No summary available.';
  const lines = [
    'TEXT SUMMARY',
    'Generated by Word Frequency Analyzer',
    `Original sentences: ${summary.originalSentenceCount}`,
    '',
  ];
  summary.sentences.forEach((s, i) => {
    lines.push(`[${i + 1}] ${s.sentence}`);
    lines.push(`    Score: ${s.score} · Sentence ${s.index + 1} of ${summary.originalSentenceCount}`);
    lines.push('');
  });
  return lines.join('\n');
}

export default function ExportPanel({ results }) {
  const wordCount = results?.words?.length || 0;
  const keywordCount = results?.keywords?.length || 0;
  const sentenceCount = results?.summary?.sentences?.length || 0;

  const exports = [
    {
      title: 'Word Frequency',
      format: 'CSV',
      description: 'Rank, word, count, percentage, stopword flag, stem',
      meta: `${wordCount.toLocaleString()} words`,
      onClick: () =>
        triggerDownload(buildWordCSV(results?.words), 'word-frequency.csv', 'text/csv'),
    },
    {
      title: 'Keywords',
      format: 'CSV',
      description: 'TF-IDF ranked keywords with scores',
      meta: `${keywordCount} keywords`,
      onClick: () =>
        triggerDownload(buildKeywordCSV(results?.keywords), 'keywords.csv', 'text/csv'),
    },
    {
      title: 'Text Summary',
      format: 'TXT',
      description: 'Extracted key sentences with importance scores',
      meta: `${sentenceCount} sentence${sentenceCount !== 1 ? 's' : ''}`,
      onClick: () =>
        triggerDownload(buildSummaryTXT(results?.summary), 'summary.txt', 'text/plain'),
    },
    {
      title: 'Full Analysis',
      format: 'JSON',
      description: 'Complete dataset — words, n-grams, keywords, summary',
      meta: 'All data',
      onClick: () =>
        triggerDownload(
          JSON.stringify(results, null, 2),
          'analysis.json',
          'application/json'
        ),
    },
  ];

  return (
    <div>
      <p className="text-[13px] text-secondary mb-6" style={{ opacity: 0.7 }}>
        Download your analysis results in your preferred format.
      </p>
      <div className="grid grid-cols-2 gap-3 max-sm:grid-cols-1">
        {exports.map((item) => (
          <div
            key={item.title}
            className="border border-border rounded-[6px] p-5 flex flex-col justify-between gap-4 hover:border-accent-muted transition-colors"
          >
            <div>
              <div className="flex items-center gap-2 mb-1.5">
                <span className="text-[13px] font-semibold text-primary">{item.title}</span>
                <span className="font-mono text-[10px] text-secondary border border-border rounded-[3px] px-1.5 py-0.5 uppercase tracking-wide">
                  {item.format}
                </span>
              </div>
              <p className="text-[12px] text-secondary leading-relaxed" style={{ opacity: 0.7 }}>
                {item.description}
              </p>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-mono text-[11px] text-secondary" style={{ opacity: 0.5 }}>
                {item.meta}
              </span>
              <button
                type="button"
                onClick={item.onClick}
                className="flex items-center gap-1.5 text-[12px] font-medium text-accent border border-accent-muted rounded-[4px] px-3 py-1.5 hover:bg-accent-light transition-colors"
              >
                <Download size={12} />
                Download
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
